//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 修改密码 的本地化字符串。
        /// </summary>
        public static string ActionChangePassword {
            get {
                return ResourceManager.GetString("ActionChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建区域 的本地化字符串。
        /// </summary>
        public static string ActionCreateArea {
            get {
                return ResourceManager.GetString("ActionCreateArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建设备 的本地化字符串。
        /// </summary>
        public static string ActionCreateDevice {
            get {
                return ResourceManager.GetString("ActionCreateDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加运输计划 的本地化字符串。
        /// </summary>
        public static string ActionCreatePlan {
            get {
                return ResourceManager.GetString("ActionCreatePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建用户 的本地化字符串。
        /// </summary>
        public static string ActionCreateUser {
            get {
                return ResourceManager.GetString("ActionCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string ActionDelete {
            get {
                return ResourceManager.GetString("ActionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string ActionEdit {
            get {
                return ResourceManager.GetString("ActionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人资料 的本地化字符串。
        /// </summary>
        public static string ActionEditProfile {
            get {
                return ResourceManager.GetString("ActionEditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string ActionLogin {
            get {
                return ResourceManager.GetString("ActionLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string ActionLogout {
            get {
                return ResourceManager.GetString("ActionLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string ActionSave {
            get {
                return ResourceManager.GetString("ActionSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看所有 的本地化字符串。
        /// </summary>
        public static string ActionViewAll {
            get {
                return ResourceManager.GetString("ActionViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电池电量告警 的本地化字符串。
        /// </summary>
        public static string AlarmBattery {
            get {
                return ResourceManager.GetString("AlarmBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 告警 的本地化字符串。
        /// </summary>
        public static string Alarms {
            get {
                return ResourceManager.GetString("Alarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 湿度告警 的本地化字符串。
        /// </summary>
        public static string AlarmTypeHumidity {
            get {
                return ResourceManager.GetString("AlarmTypeHumidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 压力告警 的本地化字符串。
        /// </summary>
        public static string AlarmTypePress {
            get {
                return ResourceManager.GetString("AlarmTypePress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温度告警 的本地化字符串。
        /// </summary>
        public static string AlarmTypeTemperature {
            get {
                return ResourceManager.GetString("AlarmTypeTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统配置 的本地化字符串。
        /// </summary>
        public static string AppSettings {
            get {
                return ResourceManager.GetString("AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区域 的本地化字符串。
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属区域 的本地化字符串。
        /// </summary>
        public static string AreaBelonged {
            get {
                return ResourceManager.GetString("AreaBelonged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区域管理 的本地化字符串。
        /// </summary>
        public static string AreaManagement {
            get {
                return ResourceManager.GetString("AreaManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建区域 的本地化字符串。
        /// </summary>
        public static string AreaManagementCreate {
            get {
                return ResourceManager.GetString("AreaManagementCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑区域 的本地化字符串。
        /// </summary>
        public static string AreaManagementEdit {
            get {
                return ResourceManager.GetString("AreaManagementEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区域名称 的本地化字符串。
        /// </summary>
        public static string AreaName {
            get {
                return ResourceManager.GetString("AreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上级区域 的本地化字符串。
        /// </summary>
        public static string AreaParent {
            get {
                return ResourceManager.GetString("AreaParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电池电量告警阈值下限（单位：%） 的本地化字符串。
        /// </summary>
        public static string BatteryThreshold {
            get {
                return ResourceManager.GetString("BatteryThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string btnOkTip {
            get {
                return ResourceManager.GetString("btnOkTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要重新分配该设备所属运输计划? 的本地化字符串。
        /// </summary>
        public static string ChangePlanTip {
            get {
                return ResourceManager.GetString("ChangePlanTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通道 的本地化字符串。
        /// </summary>
        public static string ChannelNo {
            get {
                return ResourceManager.GetString("ChannelNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 压力曲线 的本地化字符串。
        /// </summary>
        public static string chartPress {
            get {
                return ResourceManager.GetString("chartPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温度/湿度曲线 的本地化字符串。
        /// </summary>
        public static string chartTemperature {
            get {
                return ResourceManager.GetString("chartTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看详情 的本地化字符串。
        /// </summary>
        public static string chartViewDetails {
            get {
                return ResourceManager.GetString("chartViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前页 的本地化字符串。
        /// </summary>
        public static string CurrentPage {
            get {
                return ResourceManager.GetString("CurrentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实时数据 的本地化字符串。
        /// </summary>
        public static string devCurveMode {
            get {
                return ResourceManager.GetString("devCurveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 历史数据 的本地化字符串。
        /// </summary>
        public static string devHistoryMode {
            get {
                return ResourceManager.GetString("devHistoryMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备 的本地化字符串。
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交流供电 的本地化字符串。
        /// </summary>
        public static string DeviceACMode {
            get {
                return ResourceManager.GetString("DeviceACMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据相关 的本地化字符串。
        /// </summary>
        public static string DeviceData {
            get {
                return ResourceManager.GetString("DeviceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电池供电 的本地化字符串。
        /// </summary>
        public static string DeviceDCMode {
            get {
                return ResourceManager.GetString("DeviceDCMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备IMEI 的本地化字符串。
        /// </summary>
        public static string DeviceIMEI {
            get {
                return ResourceManager.GetString("DeviceIMEI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备信息 的本地化字符串。
        /// </summary>
        public static string DeviceInformation {
            get {
                return ResourceManager.GetString("DeviceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加设备 的本地化字符串。
        /// </summary>
        public static string DeviceManagementCreate {
            get {
                return ResourceManager.GetString("DeviceManagementCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑设备信息 的本地化字符串。
        /// </summary>
        public static string DeviceManagementEdit {
            get {
                return ResourceManager.GetString("DeviceManagementEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备名称 的本地化字符串。
        /// </summary>
        public static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SIM卡号 的本地化字符串。
        /// </summary>
        public static string DeviceNumber {
            get {
                return ResourceManager.GetString("DeviceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离线 的本地化字符串。
        /// </summary>
        public static string DeviceOffline {
            get {
                return ResourceManager.GetString("DeviceOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线 的本地化字符串。
        /// </summary>
        public static string DeviceOnline {
            get {
                return ResourceManager.GetString("DeviceOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电池电量 的本地化字符串。
        /// </summary>
        public static string DevicePower {
            get {
                return ResourceManager.GetString("DevicePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供电类型 的本地化字符串。
        /// </summary>
        public static string DevicePowerMode {
            get {
                return ResourceManager.GetString("DevicePowerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备类型 的本地化字符串。
        /// </summary>
        public static string DeviceType {
            get {
                return ResourceManager.GetString("DeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备列表 的本地化字符串。
        /// </summary>
        public static string devListView {
            get {
                return ResourceManager.GetString("devListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备地图 的本地化字符串。
        /// </summary>
        public static string devMapView {
            get {
                return ResourceManager.GetString("devMapView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电子邮件 的本地化字符串。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束时间 的本地化字符串。
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出数据 的本地化字符串。
        /// </summary>
        public static string ExportData {
            get {
                return ResourceManager.GetString("ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地图选点 的本地化字符串。
        /// </summary>
        public static string FetchGPSFromMap {
            get {
                return ResourceManager.GetString("FetchGPSFromMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第一页 的本地化字符串。
        /// </summary>
        public static string FirstPage {
            get {
                return ResourceManager.GetString("FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 湿度 的本地化字符串。
        /// </summary>
        public static string Humidity {
            get {
                return ResourceManager.GetString("Humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 湿度告警阈值 的本地化字符串。
        /// </summary>
        public static string HumidityThreshold {
            get {
                return ResourceManager.GetString("HumidityThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 湿度告警配置错误 的本地化字符串。
        /// </summary>
        public static string HumidityThresholdConfigError {
            get {
                return ResourceManager.GetString("HumidityThresholdConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 湿度下限 的本地化字符串。
        /// </summary>
        public static string HumidityThresholdLower {
            get {
                return ResourceManager.GetString("HumidityThresholdLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 湿度上限 的本地化字符串。
        /// </summary>
        public static string HumidityThresholdUpper {
            get {
                return ResourceManager.GetString("HumidityThresholdUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string LabelCancel {
            get {
                return ResourceManager.GetString("LabelCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是的 的本地化字符串。
        /// </summary>
        public static string LabelConfirm {
            get {
                return ResourceManager.GetString("LabelConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后一页 的本地化字符串。
        /// </summary>
        public static string LastPage {
            get {
                return ResourceManager.GetString("LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最近更新 的本地化字符串。
        /// </summary>
        public static string LastUpdate {
            get {
                return ResourceManager.GetString("LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纬度 的本地化字符串。
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string LogAction {
            get {
                return ResourceManager.GetString("LogAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作人 的本地化字符串。
        /// </summary>
        public static string LogActioner {
            get {
                return ResourceManager.GetString("LogActioner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改内容 的本地化字符串。
        /// </summary>
        public static string LogChanges {
            get {
                return ResourceManager.GetString("LogChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改日期 的本地化字符串。
        /// </summary>
        public static string LogDttm {
            get {
                return ResourceManager.GetString("LogDttm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对象 的本地化字符串。
        /// </summary>
        public static string LogType {
            get {
                return ResourceManager.GetString("LogType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 经度 的本地化字符串。
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区域管理 的本地化字符串。
        /// </summary>
        public static string MenuAreaManagement {
            get {
                return ResourceManager.GetString("MenuAreaManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作日志 的本地化字符串。
        /// </summary>
        public static string MenuAuditLog {
            get {
                return ResourceManager.GetString("MenuAuditLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备管理 的本地化字符串。
        /// </summary>
        public static string MenuDeviceManagement {
            get {
                return ResourceManager.GetString("MenuDeviceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运输计划 的本地化字符串。
        /// </summary>
        public static string MenuPlanManagement {
            get {
                return ResourceManager.GetString("MenuPlanManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户管理 的本地化字符串。
        /// </summary>
        public static string MenuUserManagement {
            get {
                return ResourceManager.GetString("MenuUserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法删除，至少需保留一个区域。 的本地化字符串。
        /// </summary>
        public static string MsgAtLeastOneAreaInSystem {
            get {
                return ResourceManager.GetString("MsgAtLeastOneAreaInSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理员账号无法删除。 的本地化字符串。
        /// </summary>
        public static string MsgCanNotDeleteAdmin {
            get {
                return ResourceManager.GetString("MsgCanNotDeleteAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该区域下有设备，无法删除 的本地化字符串。
        /// </summary>
        public static string MsgCanNotDeleteAreaWithDevice {
            get {
                return ResourceManager.GetString("MsgCanNotDeleteAreaWithDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该区域下有用户，无法删除 的本地化字符串。
        /// </summary>
        public static string MsgCanNotDeleteAreaWithUser {
            get {
                return ResourceManager.GetString("MsgCanNotDeleteAreaWithUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能设置自身为上级区域 的本地化字符串。
        /// </summary>
        public static string MsgCantSetParentAreaToSelf {
            get {
                return ResourceManager.GetString("MsgCantSetParentAreaToSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定删除“{0}”？ 的本地化字符串。
        /// </summary>
        public static string MsgDeleteAlert {
            get {
                return ResourceManager.GetString("MsgDeleteAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不匹配 的本地化字符串。
        /// </summary>
        public static string MsgFieldConfirmPassword {
            get {
                return ResourceManager.GetString("MsgFieldConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}不是合法的电子邮件地址 的本地化字符串。
        /// </summary>
        public static string MsgFieldEmail {
            get {
                return ResourceManager.GetString("MsgFieldEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}长度应该为{1} 的本地化字符串。
        /// </summary>
        public static string MsgFieldExactLength {
            get {
                return ResourceManager.GetString("MsgFieldExactLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}长度应该在{2}和{1}之间 的本地化字符串。
        /// </summary>
        public static string MsgFieldLength {
            get {
                return ResourceManager.GetString("MsgFieldLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}不是有效的电话号码 的本地化字符串。
        /// </summary>
        public static string MsgFieldPhone {
            get {
                return ResourceManager.GetString("MsgFieldPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必填项 的本地化字符串。
        /// </summary>
        public static string MsgFieldRequired {
            get {
                return ResourceManager.GetString("MsgFieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名或者密码错误 的本地化字符串。
        /// </summary>
        public static string MsgPasswordNotMatch {
            get {
                return ResourceManager.GetString("MsgPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名已存在 的本地化字符串。
        /// </summary>
        public static string MsgUserNameAlreadyExists {
            get {
                return ResourceManager.GetString("MsgUserNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一页 的本地化字符串。
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码确认 的本地化字符串。
        /// </summary>
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话 的本地化字符串。
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电量(%) 的本地化字符串。
        /// </summary>
        public static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 压力 的本地化字符串。
        /// </summary>
        public static string Press {
            get {
                return ResourceManager.GetString("Press", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 压力告警阈值（单位：kPa） 的本地化字符串。
        /// </summary>
        public static string PressThreshold {
            get {
                return ResourceManager.GetString("PressThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 压力告警配置错误 的本地化字符串。
        /// </summary>
        public static string PressThresholdConfigError {
            get {
                return ResourceManager.GetString("PressThresholdConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 压力告警下限 的本地化字符串。
        /// </summary>
        public static string PressThresholdLower {
            get {
                return ResourceManager.GetString("PressThresholdLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 压力告警上限 的本地化字符串。
        /// </summary>
        public static string PressThresholdUpper {
            get {
                return ResourceManager.GetString("PressThresholdUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一页 的本地化字符串。
        /// </summary>
        public static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看 的本地化字符串。
        /// </summary>
        public static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 武钢江南中燃燃气（武汉）有限公司压力监控系统 的本地化字符串。
        /// </summary>
        public static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始计划 的本地化字符串。
        /// </summary>
        public static string StartPlan {
            get {
                return ResourceManager.GetString("StartPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起始点 的本地化字符串。
        /// </summary>
        public static string StartPoint {
            get {
                return ResourceManager.GetString("StartPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始时间 的本地化字符串。
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止计划 的本地化字符串。
        /// </summary>
        public static string StopPlan {
            get {
                return ResourceManager.GetString("StopPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换区域 的本地化字符串。
        /// </summary>
        public static string SwitchArea {
            get {
                return ResourceManager.GetString("SwitchArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温度(℃) 的本地化字符串。
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温度告警阈值（单位： ℃） 的本地化字符串。
        /// </summary>
        public static string TemperatureThreshold {
            get {
                return ResourceManager.GetString("TemperatureThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温度告警配置错误 的本地化字符串。
        /// </summary>
        public static string TemperatureThresholdConfigError {
            get {
                return ResourceManager.GetString("TemperatureThresholdConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温度下限 的本地化字符串。
        /// </summary>
        public static string TemperatureThresholdLower {
            get {
                return ResourceManager.GetString("TemperatureThresholdLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温度上限 的本地化字符串。
        /// </summary>
        public static string TemperatureThresholdUpper {
            get {
                return ResourceManager.GetString("TemperatureThresholdUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户管理 的本地化字符串。
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建用户 的本地化字符串。
        /// </summary>
        public static string UserManagementCreate {
            get {
                return ResourceManager.GetString("UserManagementCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑用户信息 的本地化字符串。
        /// </summary>
        public static string UserManagementEdit {
            get {
                return ResourceManager.GetString("UserManagementEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看运输踪迹 的本地化字符串。
        /// </summary>
        public static string ViewPlanTrace {
            get {
                return ResourceManager.GetString("ViewPlanTrace", resourceCulture);
            }
        }
    }
}
